-- Refresh tokens become revocable by making the database, not the token, the
-- authority on whether a session is still alive.
--
-- Until now the refresh JWT was self-contained: valid for 24 hours because it
-- said so, with nowhere to record that a user had logged out. The token now
-- carries only a jti, and everything that decides whether it still counts lives
-- in this table.

CREATE TABLE public.refresh_tokens (
    id         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- The only claim in the JWT. Unique because it is the lookup key.
    jti        text    NOT NULL,
    -- Groups every token descended from one login, so ending one session
    -- leaves the user's other devices alone.
    family_id  text    NOT NULL,
    user_id    integer NOT NULL,
    -- timestamptz, deliberately unlike every other table here.
    --
    -- The rest of the schema uses `timestamp without time zone`, and those
    -- columns are only ever ordered or displayed. These are compared against
    -- Go's clock, and a naive column stores whatever local time the process
    -- happened to be in: running in CEST wrote values two hours ahead of the
    -- database's own now(). Read back, that made every elapsed-time
    -- calculation negative — which silently held the grace window open and
    -- let tokens outlive their expiry.
    expires_at timestamptz NOT NULL,
    -- NULL means active. A timestamp rather than a boolean because the grace
    -- window needs to know how long ago it was consumed.
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_jti_key UNIQUE (jti)
);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Revoking a family on reuse detection.
CREATE INDEX refresh_tokens_family_id_idx ON public.refresh_tokens (family_id);
-- The cleanup DELETE that runs on login.
CREATE INDEX refresh_tokens_expires_at_idx ON public.refresh_tokens (expires_at);
