-- The catalog becomes IGDB-native.
--
-- games.id stays a surrogate key. Using IGDB's ids as the primary key would be
-- the same bet that Steam's ids were, and this migration is the cost of having
-- lost that bet once.
--
-- Crucially the seven existing rows keep their ids, so user_games needs no
-- changes at all: 14 list entries stay valid with their categories, ratings and
-- reviews. The old Steam numbers survive as meaningless surrogates.

-- One table for the three lists IGDB attaches to a game. Three tables would
-- mean writing the same import, join and query three times, forever.
CREATE TABLE public.tags (
    id         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Which list this belongs to. Called facet, not kind, because games.kind
    -- below means something entirely different.
    facet      text NOT NULL,
    igdb_id    integer NOT NULL,
    name       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT tags_pkey PRIMARY KEY (id),
    CONSTRAINT tags_facet_check CHECK (facet IN ('genre', 'theme', 'game_mode')),
    -- What makes import idempotent without a pre-flight check.
    CONSTRAINT tags_facet_igdb_id_key UNIQUE (facet, igdb_id)
);

CREATE TABLE public.games_tags (
    game_id integer NOT NULL,
    tag_id  integer NOT NULL,

    CONSTRAINT games_tags_pkey PRIMARY KEY (game_id, tag_id),
    -- CASCADE both ways, unlike user_games.game_id: a lost tag link destroys
    -- nothing a person wrote.
    CONSTRAINT games_tags_game_id_fkey FOREIGN KEY (game_id)
        REFERENCES public.games(id) ON DELETE CASCADE,
    CONSTRAINT games_tags_tag_id_fkey FOREIGN KEY (tag_id)
        REFERENCES public.tags(id) ON DELETE CASCADE
);

CREATE INDEX games_tags_tag_id_idx ON public.games_tags (tag_id);

ALTER TABLE public.games ADD COLUMN igdb_id integer;
-- Default so the column can be NOT NULL immediately; every real row gets a
-- value from IGDB on import.
ALTER TABLE public.games ADD COLUMN kind text NOT NULL DEFAULT 'unknown';

-- The remap. Looked up against live IGDB; note 334254 rather than 334647 for
-- GTA V Enhanced - both exist with the same title and date, and 334647 is the
-- retail bundle rather than the game.
UPDATE public.games SET igdb_id = 242408, kind = 'main_game'     WHERE id = 730;
UPDATE public.games SET igdb_id = 1942,   kind = 'main_game'     WHERE id = 292030;
UPDATE public.games SET igdb_id = 9630,   kind = 'main_game'     WHERE id = 377160;
UPDATE public.games SET igdb_id = 19457,  kind = 'remaster'      WHERE id = 489830;
UPDATE public.games SET igdb_id = 25076,  kind = 'main_game'     WHERE id = 1174180;
UPDATE public.games SET igdb_id = 335833, kind = 'main_game'     WHERE id = 1395520;
UPDATE public.games SET igdb_id = 334254, kind = 'expanded_game' WHERE id = 3240220;

-- A game with no IGDB identity cannot exist under the new rule. With the seven
-- above mapped this deletes nothing; if it ever deletes a row that a list
-- points at, the RESTRICT on user_games.game_id stops the migration loudly,
-- which is the correct outcome.
DELETE FROM public.games WHERE igdb_id IS NULL;

ALTER TABLE public.games ALTER COLUMN igdb_id SET NOT NULL;
ALTER TABLE public.games ADD CONSTRAINT games_igdb_id_key UNIQUE (igdb_id);

-- The seven games' real IGDB data: titles, covers, dates and tags.
--
-- SQL cannot call IGDB, so this was generated once against the live API and
-- hardcoded, like the ids above. Without it the remapped games would carry
-- their old Steam titles and covers and no genres at all - a visible
-- regression, since the seeded data at least had genres.

UPDATE public.games SET title = 'Counter-Strike 2', image = 'https://images.igdb.com/igdb/image/upload/t_cover_big/coaczd.jpg', release_date = '2023-09-27' WHERE id = 730;
UPDATE public.games SET title = 'The Witcher 3: Wild Hunt', image = 'https://images.igdb.com/igdb/image/upload/t_cover_big/coaarl.jpg', release_date = '2015-05-19' WHERE id = 292030;
UPDATE public.games SET title = 'Fallout 4', image = 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1yc6.jpg', release_date = '2015-11-09' WHERE id = 377160;
UPDATE public.games SET title = 'The Elder Scrolls V: Skyrim - Special Edition', image = 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1vco.jpg', release_date = '2016-10-27' WHERE id = 489830;
UPDATE public.games SET title = 'Red Dead Redemption 2', image = 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg', release_date = '2018-10-26' WHERE id = 1174180;
UPDATE public.games SET title = 'The Séance of Blake Manor', image = 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9jkt.jpg', release_date = '2025-10-27' WHERE id = 1395520;
UPDATE public.games SET title = 'Grand Theft Auto V Enhanced', image = 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9hz1.jpg', release_date = '2025-03-04' WHERE id = 3240220;

INSERT INTO public.tags (facet, igdb_id, name) VALUES ('game_mode', 1, 'Single player');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('game_mode', 2, 'Multiplayer');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('game_mode', 3, 'Co-operative');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('genre', 5, 'Shooter');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('genre', 9, 'Puzzle');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('genre', 10, 'Racing');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('genre', 12, 'Role-playing (RPG)');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('genre', 24, 'Tactical');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('genre', 31, 'Adventure');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 1, 'Action');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 17, 'Fantasy');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 18, 'Science fiction');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 21, 'Survival');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 22, 'Historical');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 23, 'Stealth');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 31, 'Drama');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 33, 'Sandbox');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 38, 'Open world');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 39, 'Warfare');
INSERT INTO public.tags (facet, igdb_id, name) VALUES ('theme', 43, 'Mystery');

-- Joined through public.games rather than selecting a literal game id.
--
-- These were `SELECT 730, id FROM tags WHERE ...`, which produces a row
-- whenever the *tag* exists — whether or not the game does. That worked on the
-- only database that had ever run it, because the seven games were already
-- there from sql/seed.sql. On an empty database the UPDATEs above match
-- nothing, games is empty, and the first insert dies on
-- games_tags_game_id_fkey: migrations could not be applied to a fresh
-- database at all, which would have surfaced on the first real deployment.
--
-- Joining makes each statement a no-op when its game is absent and produce
-- exactly the same 50 rows when it is present.
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 730 AND t.facet = 'genre' AND t.igdb_id = 5;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 730 AND t.facet = 'genre' AND t.igdb_id = 24;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 730 AND t.facet = 'theme' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 730 AND t.facet = 'theme' AND t.igdb_id = 39;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 730 AND t.facet = 'game_mode' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 730 AND t.facet = 'game_mode' AND t.igdb_id = 2;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 292030 AND t.facet = 'genre' AND t.igdb_id = 12;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 292030 AND t.facet = 'genre' AND t.igdb_id = 31;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 292030 AND t.facet = 'theme' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 292030 AND t.facet = 'theme' AND t.igdb_id = 17;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 292030 AND t.facet = 'theme' AND t.igdb_id = 38;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 292030 AND t.facet = 'game_mode' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'genre' AND t.igdb_id = 5;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'genre' AND t.igdb_id = 12;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'theme' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'theme' AND t.igdb_id = 18;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'theme' AND t.igdb_id = 21;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'theme' AND t.igdb_id = 23;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'theme' AND t.igdb_id = 33;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'theme' AND t.igdb_id = 38;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 377160 AND t.facet = 'game_mode' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'genre' AND t.igdb_id = 12;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'genre' AND t.igdb_id = 31;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'theme' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'theme' AND t.igdb_id = 17;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'theme' AND t.igdb_id = 22;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'theme' AND t.igdb_id = 33;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'theme' AND t.igdb_id = 38;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 489830 AND t.facet = 'game_mode' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'genre' AND t.igdb_id = 5;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'genre' AND t.igdb_id = 12;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'genre' AND t.igdb_id = 31;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'theme' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'theme' AND t.igdb_id = 31;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'theme' AND t.igdb_id = 38;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'game_mode' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'game_mode' AND t.igdb_id = 2;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1174180 AND t.facet = 'game_mode' AND t.igdb_id = 3;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1395520 AND t.facet = 'genre' AND t.igdb_id = 9;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1395520 AND t.facet = 'genre' AND t.igdb_id = 31;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1395520 AND t.facet = 'theme' AND t.igdb_id = 43;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 1395520 AND t.facet = 'game_mode' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'genre' AND t.igdb_id = 5;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'genre' AND t.igdb_id = 10;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'genre' AND t.igdb_id = 31;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'theme' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'theme' AND t.igdb_id = 38;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'game_mode' AND t.igdb_id = 1;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'game_mode' AND t.igdb_id = 2;
INSERT INTO public.games_tags (game_id, tag_id) SELECT g.id, t.id FROM public.games g, public.tags t WHERE g.id = 3240220 AND t.facet = 'game_mode' AND t.igdb_id = 3;

-- Superseded by tags. Their 15 seeded rows were test data.
DROP TABLE public.games_genres;
DROP TABLE public.genres;

-- Every games row was inserted with a client-supplied Steam id, so the identity
-- sequence still sits near 1. The first generated id would be 1, and left alone
-- the sequence would eventually walk into 730 - as a duplicate key on a table
-- that had been working for months.
DO $$
DECLARE next_id bigint;
BEGIN
    SELECT coalesce(max(id), 0) + 1 INTO next_id FROM public.games;
    EXECUTE format('ALTER TABLE public.games ALTER COLUMN id RESTART WITH %s', next_id);
END $$;
