-- Lossy, unavoidably: the tags and every game's IGDB identity are dropped, and
-- genres comes back empty because its old contents were replaced rather than
-- moved. Rolling back leaves a catalog with no genres at all.

CREATE TABLE public.genres (
    id         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    genre      character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE public.games_genres (
    id       integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    game_id  integer,
    genre_id integer,
    CONSTRAINT games_genres_pkey PRIMARY KEY (id)
);

ALTER TABLE public.games DROP CONSTRAINT games_igdb_id_key;
ALTER TABLE public.games DROP COLUMN igdb_id;
ALTER TABLE public.games DROP COLUMN kind;

DROP TABLE public.games_tags;
DROP TABLE public.tags;
