-- The catalog becomes IGDB-native.
--
-- games.id stays a surrogate key. Using IGDB's ids as the primary key would be
-- the same bet that Steam's ids were, and this migration is the cost of having
-- lost that bet once.
--
-- Crucially the seven existing rows keep their ids, so user_games needs no
-- changes at all: 14 list entries stay valid with their categories, ratings and
-- reviews. The old Steam numbers survive as meaningless surrogates.

-- One table for the three lists IGDB attaches to a game. Three tables would
-- mean writing the same import, join and query three times, forever.
CREATE TABLE public.tags (
    id         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Which list this belongs to. Called facet, not kind, because games.kind
    -- below means something entirely different.
    facet      text NOT NULL,
    igdb_id    integer NOT NULL,
    name       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT tags_pkey PRIMARY KEY (id),
    CONSTRAINT tags_facet_check CHECK (facet IN ('genre', 'theme', 'game_mode')),
    -- What makes import idempotent without a pre-flight check.
    CONSTRAINT tags_facet_igdb_id_key UNIQUE (facet, igdb_id)
);

CREATE TABLE public.games_tags (
    game_id integer NOT NULL,
    tag_id  integer NOT NULL,

    CONSTRAINT games_tags_pkey PRIMARY KEY (game_id, tag_id),
    -- CASCADE both ways, unlike user_games.game_id: a lost tag link destroys
    -- nothing a person wrote.
    CONSTRAINT games_tags_game_id_fkey FOREIGN KEY (game_id)
        REFERENCES public.games(id) ON DELETE CASCADE,
    CONSTRAINT games_tags_tag_id_fkey FOREIGN KEY (tag_id)
        REFERENCES public.tags(id) ON DELETE CASCADE
);

CREATE INDEX games_tags_tag_id_idx ON public.games_tags (tag_id);

ALTER TABLE public.games ADD COLUMN igdb_id integer;
-- Default so the column can be NOT NULL immediately; every real row gets a
-- value from IGDB on import.
ALTER TABLE public.games ADD COLUMN kind text NOT NULL DEFAULT 'unknown';

-- The remap. Looked up against live IGDB; note 334254 rather than 334647 for
-- GTA V Enhanced - both exist with the same title and date, and 334647 is the
-- retail bundle rather than the game.
UPDATE public.games SET igdb_id = 242408, kind = 'main_game'     WHERE id = 730;
UPDATE public.games SET igdb_id = 1942,   kind = 'main_game'     WHERE id = 292030;
UPDATE public.games SET igdb_id = 9630,   kind = 'main_game'     WHERE id = 377160;
UPDATE public.games SET igdb_id = 19457,  kind = 'remaster'      WHERE id = 489830;
UPDATE public.games SET igdb_id = 25076,  kind = 'main_game'     WHERE id = 1174180;
UPDATE public.games SET igdb_id = 335833, kind = 'main_game'     WHERE id = 1395520;
UPDATE public.games SET igdb_id = 334254, kind = 'expanded_game' WHERE id = 3240220;

-- A game with no IGDB identity cannot exist under the new rule. With the seven
-- above mapped this deletes nothing; if it ever deletes a row that a list
-- points at, the RESTRICT on user_games.game_id stops the migration loudly,
-- which is the correct outcome.
DELETE FROM public.games WHERE igdb_id IS NULL;

ALTER TABLE public.games ALTER COLUMN igdb_id SET NOT NULL;
ALTER TABLE public.games ADD CONSTRAINT games_igdb_id_key UNIQUE (igdb_id);

-- Superseded by tags. Their 15 seeded rows were test data.
DROP TABLE public.games_genres;
DROP TABLE public.genres;

-- Every games row was inserted with a client-supplied Steam id, so the identity
-- sequence still sits near 1. The first generated id would be 1, and left alone
-- the sequence would eventually walk into 730 - as a duplicate key on a table
-- that had been working for months.
DO $$
DECLARE next_id bigint;
BEGIN
    SELECT coalesce(max(id), 0) + 1 INTO next_id FROM public.games;
    EXECUTE format('ALTER TABLE public.games ALTER COLUMN id RESTART WITH %s', next_id);
END $$;
