-- The list. One row per (user, game), enforced by the unique constraint below.
--
-- Category is a column on the entry rather than a separate list the game
-- belongs to. That is what makes moving a game an UPDATE of one row, which is
-- what lets the rating and review survive the move.

CREATE TABLE public.user_games (
    id         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    integer NOT NULL,
    game_id    integer NOT NULL,
    category   text    NOT NULL,
    rating     smallint,
    review     text,
    -- Column only, deliberately. VISION.md keeps hours optional and
    -- unimportant; nothing writes it yet.
    hours      integer,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT user_games_pkey PRIMARY KEY (id),
    CONSTRAINT user_games_user_id_game_id_key UNIQUE (user_id, game_id),
    CONSTRAINT user_games_category_check CHECK (category IN ('finished', 'currently_playing', 'want_to_play')),
    CONSTRAINT user_games_rating_check   CHECK (rating BETWEEN 1 AND 10),
    CONSTRAINT user_games_hours_check    CHECK (hours >= 0)
);

-- Deleting an account takes its list: these rows mean nothing without a user.
ALTER TABLE ONLY public.user_games
    ADD CONSTRAINT user_games_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- RESTRICT, not CASCADE, on purpose. /admin/games has no role check, so any
-- logged-in user can delete any game. Under CASCADE one careless delete would
-- silently destroy every user's rating and review for that game. Under
-- RESTRICT the delete fails and the reviews survive. A catalog row can be
-- re-fetched from IGDB; a friend's two sentences cannot.
ALTER TABLE ONLY public.user_games
    ADD CONSTRAINT user_games_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games(id) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX user_games_user_id_category_idx ON public.user_games (user_id, category);
