CREATE TABLE public.genres (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    genre character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE public.games (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(512),
    image character varying(255),
    release_date date,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT games_pkey PRIMARY KEY (id)
);

CREATE TABLE public.games_genres (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    game_id integer,
    genre_id integer,
    CONSTRAINT games_genres_pkey PRIMARY KEY (id)
);

CREATE TABLE public.users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255),
    email character varying(255),
    password character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE ONLY public.games_genres
    ADD CONSTRAINT games_genres_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES public.genres(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.games_genres
    ADD CONSTRAINT games_genres_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON UPDATE CASCADE ON DELETE CASCADE;
