package main

import (
	"flag"
	"fmt"
	"log"
	"net/mail"
	"os"
	"time"
	"toomanyhours-api/internal/igdb"
	"toomanyhours-api/internal/ratelimit"
	"toomanyhours-api/internal/repository/dbrepo"

	"github.com/gin-gonic/gin/binding"
	"github.com/go-playground/validator/v10"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

// apiVersion is the API's own version, independent of the frontend's: two
// repositories with two histories.
//
// A constant rather than an env var. It used to be os.Getenv("VERSION") read
// from .env, which is gitignored — so GET / reported an empty string on any
// checkout but this one. A version that only exists on one machine is not a
// version.
const apiVersion = "0.4.0"

type application struct {
	DSN          string
	Domain       string
	GormDB       *gorm.DB
	DB           *dbrepo.PostgresDBRepo
	auth         Auth
	JWTSecret    string
	JWTIssuer    string
	JWTAudience  string
	CookieDomain string
	// Login limiters. Two keys because they defend different attacks: per-IP
	// catches password spraying across many accounts, per-email catches a
	// brute force against one account even from rotating addresses.
	loginIPLimiter    *ratelimit.Limiter
	loginEmailLimiter *ratelimit.Limiter
	// Availability checks are unauthenticated and hit the database on a
	// debounced keystroke. The frontend's debounce is a courtesy this endpoint
	// cannot rely on.
	usernameCheckLimiter *ratelimit.Limiter
	// How long a just-consumed refresh token is still accepted as a concurrent
	// retry rather than a replay. Configurable so tests can drive it to zero.
	RefreshGrace     time.Duration
	IGDBClientID     string
	IGDBClientSecret string
	// nil when credentials are unset. The app still boots and search answers
	// 503, so this project runs for anyone without a Twitch application.
	IGDB *igdb.Client
}

func emailValidator(fl validator.FieldLevel) bool {
	if _, err := mail.ParseAddress(fl.Field().String()); err == nil {
		return true
	}
	return false
}

func init() {
	if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
		v.RegisterValidation("email", emailValidator)
	}
}

// Schema fix for genre ID generation
// func (app *application) runSchemaFix() error {
// 	fmt.Println("Running genre ID generation fix...")
// 	// This command changes the column behavior to allow explicit IDs
// 	stmt := `ALTER TABLE genres ALTER COLUMN id SET GENERATED BY DEFAULT`

// 	result := app.GormDB.Exec(stmt)
// 	if result.Error != nil {
// 		return fmt.Errorf("failed to run schema fix: %w", result.Error)
// 	}
// 	fmt.Println("Schema fix applied successfully.")
// 	return nil
// }

func main() {
	// set application config
	var app application
	godotenv.Load()

	// get environment variables
	port := os.Getenv("PORT")
	dbUser := os.Getenv("DB_USER")
	dbPass := os.Getenv("DB_PASSWORD")
	dbName := os.Getenv("DB_NAME")
	dbPort := os.Getenv("DB_PORT")
	dbSslmode := os.Getenv("DB_SSLMODE")
	dbTimezone := os.Getenv("DB_TIMEZONE")
	dbTimeout := os.Getenv("DB_CONNECT_TIMEOUT")
	dbHost := os.Getenv("DB_HOST")

	// read from command line
	flag.StringVar(
		&app.DSN,
		"dsn",
		fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=%s timezone=%s connect_timeout=%s", dbHost, dbPort, dbUser, dbPass, dbName, dbSslmode, dbTimezone, dbTimeout),
		"Postgres connection string",
	)
	flag.StringVar(
		&app.JWTSecret, "jwt-secret", os.Getenv("JWT_SECRET"), "Signing secret")
	flag.StringVar(
		&app.JWTIssuer, "jwt-issuer", "localhost", "Signing issuer")
	flag.StringVar(
		&app.JWTAudience, "jwt-audience", "localhost", "Signing audience")
	flag.StringVar(
		&app.CookieDomain, "cookie-domain", "localhost", "Cookie domain")
	flag.StringVar(
		&app.Domain, "domain", "localhost", "Domain")
	flag.DurationVar(
		&app.RefreshGrace, "refresh-grace", 10*time.Second,
		"How long a consumed refresh token is still accepted, for concurrent tabs")
	flag.StringVar(
		&app.IGDBClientID, "igdb-client-id", os.Getenv("IGDB_CLIENT_ID"),
		"Twitch application client id, used for IGDB")
	flag.StringVar(
		&app.IGDBClientSecret, "igdb-client-secret", os.Getenv("IGDB_CLIENT_SECRET"),
		"Twitch application client secret, used for IGDB")
	flag.Parse()

	if app.IGDBClientID != "" && app.IGDBClientSecret != "" {
		app.IGDB = igdb.New(igdb.Config{
			ClientID:     app.IGDBClientID,
			ClientSecret: app.IGDBClientSecret,
		})
	} else {
		// Not fatal on purpose: everything except game search still works, so
		// the project runs without a Twitch application of your own.
		log.Println("IGDB credentials not set; game search will answer 503")
	}

	// connect to database
	gormConn, err := app.connectGormDB()
	if err != nil {
		log.Fatal(err)
	}
	app.GormDB = gormConn
	app.DB = &dbrepo.PostgresDBRepo{GormDB: gormConn}

	// if err := app.runSchemaFix(); err != nil {
	// 	log.Fatal(err)
	// }

	db, _ := app.GormDB.DB()
	defer db.Close()

	app.auth = Auth{
		Issuer:             app.JWTIssuer,
		Audience:           app.JWTAudience,
		Secret:             app.JWTSecret,
		TokenExpiry:        time.Minute * 15,
		RefreshTokenExpiry: time.Hour * 24,
		CookiePath:         "/",                    // root path
		CookieName:         "__Host-refresh_token", // secure, httponly, samesite=lax cookie name
		CookieDomain:       "",
	}

	// 20 failures per 15 minutes from one address. Far more than a person who
	// forgot their password produces, low enough to cap how much bcrypt work a
	// single attacker can force.
	app.loginIPLimiter = ratelimit.New(20, 15*time.Minute)

	// 5 failures per minute against one account. The window is short on
	// purpose: anyone who knows a friend's email can hold that account blocked
	// by failing logins, so the block has to expire fast. It still caps a
	// distributed attacker at 300 guesses an hour, which against bcrypt is
	// nothing.
	app.loginEmailLimiter = ratelimit.New(5, time.Minute)

	// 60 a minute per address. A person typing a name produces a handful;
	// this is generous for them and still caps a script.
	app.usernameCheckLimiter = ratelimit.New(60, time.Minute)

	log.Printf("starting tooManyHours API server on %s:%s", app.Domain, port)
	log.Printf("version: %s", apiVersion)

	// start a web server
	err = app.routes().Run(fmt.Sprintf(":%s", port))
	if err != nil {
		log.Fatal(err)
	}
}
